### ISSUE TITLE
TESTS\filesystem\parallel - Not parallel

### ISSUE THREAD

**Issue by deepikabhavnani** [ARMmbed/mbed-littlefs#4]
Test cases in `TESTS\filesystem\parallel` folder are not actually read/write to files in parallel test case. It is actually read/write to multiple files sequentially.

**Comment by geky** [comment]
Although it's not completely writing the entire file sequentially. My mind was blanking on a better name at the time though I'm open to changing it. There are not currently any multithreaded tests.

How about "interspersed"?

**Comment by deepikabhavnani** [comment]
I am planning on adding multithreaded cases, to see if that causes corruption. In order to avoid clash, i added the issue. I am fine with any naming.

**Comment by geky** [comment]
Should be fixed with this commit: https://github.com/ARMmbed/mbed-littlefs/commit/5afec680738652f0a8f4e21a94d103c0491c5f31
