### ISSUE TITLE
Query: fs.remove to file which is open 

### ISSUE THREAD

**Issue by deepikabhavnani** [ARMmbed/mbed-littlefs#5]
https://github.com/ARMmbed/mbed-littlefs/blob/master/TESTS/filesystem/parallel/main.cpp#L295

As per the test case above, remove to file opened for (write/read) is successful without closing.
Shouldn't filesystem  deny removal of files in use?

**Comment by geky** [comment]
Nope, removal while open is what is being tested.

It's valid to remove a file while the file is open. The open file remains readable/writable, but any further opens on the file should fail. It's up to the filesystem to track these ghost files.

https://stackoverflow.com/a/2031100
