### ISSUE TITLE
LittleFS only runs on block devices with at least 32 blocks of space

### ISSUE THREAD

**Issue by marcuschangarm** [ARMmbed/mbed-littlefs#8]
It would be useful if the only limit was available space and not a fixed number of blocks. Currently you get an assert on line 1875 in lfs.c if the block device contains less than 32 blocks.

**Comment by geky** [comment]
Thanks for reporting, should be fixed now: https://github.com/ARMmbed/mbed-littlefs/commit/785b0b4bc4552100619ee22aedd64523b9341f0f

**Comment by geky** [comment]
closing, please reopen if this hasn't been fixed
